### PR TITLE
fix Error from sublime_plugin.py

### PR DESCRIPTION
**Pull request by matiaspub**
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 356, in run_
TypeError: run() got an unexpected keyword argument 'url'

Sublime Text 2, Dev Channel, Build 2220

### CODE REVIEW

**Comment by 9thport** [comment]
+1

**Comment by Benaiah** [comment]
+1

**Comment by kemayo** [comment]
This is non-mergeable. In fact, it shows that you changed every single line of the plugin -- did you change line endings?

**Comment by kemayo** [comment]
I'm closing this, for lack of response.

**Pull request closed without merging**
